sudo yum install docker
sudo systemctl start docker
sudo systemctl enable docker
vim dockerfile
FROM ubuntu:24.04
RUN apt-get update && apt-get install apache2 -y && apt-get clean
EXPOSE 80
CMD ["apachectl","-D","FOREGROUND"]
wq!

sudo docker build -t custom .
sudo docker ps -a 
sudo docker images
sudo docker run -d -p 80:80 custom
hit the ip of intance 1st add port 80 in the Security group.
